#!/bin/sh
STATE="$(sysctl hw.acpi.battery.state | awk '{ print $2 }')"
CHARGE="$(sysctl hw.acpi.battery.life | awk '{ print $2 }')"

case $STATE in
		1)
			#discharging
			OUTPUT="  $CHARGE%% "
			;;
		2)
			#charging
			OUTPUT="  $CHARGE%% "
			;;
		7)
			#no battery attached, plugged.
			OUTPUT="N/A"
			;;
		0)
			#fully charged, or at least we think so
			OUTPUT="󱟢 $CHARGE%% "
			;;
		*)
			OUTPUT="ERR"
			;;
esac
printf "$OUTPUT"
