#!/bin/sh

# Интервал обновления в секундах
interval=1

# Проверяем, что аргумент был передан и является числом
if [ $# -eq 1 ]; then
interval=$1
fi

# Функция для получения и вывода нагрузки процессора
# Используем vmstat для получения информации о загрузке процессора
vmstat_output=$(vmstat 1 2 | tail -n 1)
user_cpu=$(echo $vmstat_output | awk '{print $17}')
echo "$user_cpu%"
